[workspace]
members = [
    "common",
    "block-hash-store",
    "vrf-coordinator",
    "tests",
    "tests/test-session",
]

default-members = ["common"]

[profile.release]
overflow-checks = true
lto = true
codegen-units = 1
opt-level = "s"
